### ISSUE TITLE
2 characters command

### ISSUE THREAD

**Issue by pickfire** [fishery/fin#3]
`fin ls` and `fin rm`.

In My Humber Opinion, why not `fin up`? Maybe other to consider as well but `fin up` looks nice.

And by the way, I like the word `plug` more than `bundle` after seeing `vim-plug` as the successor of `bundle` (a lot of those plugin manager named it bundle or so).

**Comment by bucaran** [comment]
Hey, @pickfire. `fin up` already works.

fin knows the following aliases by default:

````
fin i in install # or nothing this is the default
fin u up update
fin l ls list
fin r rm remove uninstall
fin h help
```

**Comment by pickfire** [comment]
@bucaran, https://github.com/pickfire/fin/commit/6768a4c75211f9439ceedda7c3bdc0dbb94fd39d but I can't create a pull request.

Yeah, I like `fishfile` more. Extra idea, `fishes`.

I am actually just suggesting to use `fin up` wording in the README instead of `fin update` to look cool.

**Comment by bucaran** [comment]
@pickfire 

OMG what wizardry is this you are showing me?!?

```
curl -sLo ~/.config/fish/functions/fin.fish --create-dirs git.io/fin
```

**Comment by pickfire** [comment]
@bucaran, it's black magic named **ABRACADABRA!**, I have tested it and it worked. Copied from vim-plug:
```fish
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

**Comment by bucaran** [comment]
Yes, I just tried it and it did work, sweet. Let me push a few more commits before 1.0 and you can send me a PR.

**Comment by pickfire** [comment]
@bucaran, I would submit some comments in the fin.fish (future) to show others how to use it if someone had viewed the file.

**Comment by bucaran** [comment]
@pickfire What do you mean?

**Comment by pickfire** [comment]
@bucaran https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1-L58

**Comment by bucaran** [comment]
Got it. Well, I don't know, there is already a README and a manpage. What more help does the user need? This is the simplest CLI you could possibly imagine, but some help is okay.

**Comment by bucaran** [comment]
@alphapapa

What do you think about this?

curl -sLo ~/.config/fish/functions/fin.fish --create-dirs git.io/fin

**Comment by herrbischoff** [comment]
@bucaran: taking cues from package managers, some kind of `[whatever]file` naming scheme feels familiar. Apart from `finfile` it gets difficult to find a fitting name. I agree that `fishfile` is already used by Fisherman and should not be repurposed. Here are a couple of alternative naming ideas off the top of my head:

- `finfile` (as suggested)
- `seafile` (although there's [this](https://www.seafile.com))
- `catchfile`
- `finlets`
- `fins`
- `scales`
- `fishbundle`

Also:

> curl -sLo ~/.config/fish/functions/fin.fish --create-dirs git.io/fin

Nice! :)

**Comment by bucaran** [comment]
@herrbischoff It would be great if we could decide on a single name for everyone, including fisherman.

Internally, we would still try to read all the files, but on the surface, we would only talk about __file__, and eventually update the code after no one remembers.

**Comment by herrbischoff** [comment]
@bucaran: In that case, I'd vote for `fishfile` as it's the most generic and most fitting name at the same time, which is also not tied to either project name. Fisherman should adopt the new format as soon as possible then.

**Comment by rolyreyes** [comment]
Maybe `fisherfile` and `finfile`? If not, I really like @herrbischoff's suggestion.

**Comment by bucaran** [comment]
@pickfire `curl -#Lo ~/.config/fish/functions/fin.fish --create-dirs git.io/fin` :grinning:

**Comment by bucaran** [comment]
@herrbischoff So, fisherman currently uses a _fishfile_, and this file is essentially the same as fin's _bundle_, except that fin has the ability to satisfy modifications done to that file as well as find missing deps from plugins declared therein.

For consistency with the naming conventions of other systems out there, I think bundle makes sense, and it's easy to explain. For consistency with the terminology we've already created with fisherman, fishfile may be preferable, but then again, we can update fisherman's docs to say bundle (it already does uses both fishfile and bundle internally).

**Comment by pickfire** [comment]
@bucaran, I asked to put the guide in `fin.fish` not because it already exist in README.md, but to let users check easily for some guide offline. One question, do you notice how does one install fin?

> @pickfire curl -#Lo ~/.config/fish/functions/fin.fish --create-dirs git.io/fin

A **vote** for `fishfile`.

**Comment by bucaran** [comment]
Yup, I tried it and it worked nicely. I've updated the README too, thanks to you.

I am ready to push 1.0.0 as soon as we decide on what to use bundle, fishfile, etc. It seems @herrbischoff @pickfire and @rolyreyes all agree that fishfile or finfile is the best choice.

What does @jethrokuan or @orangecms think about it?

**Comment by jethrokuan** [comment]
I think `fishfile` works best.

**Comment by herrbischoff** [comment]
I'm not too passionate either way. Just a couple of "prior art" examples of the `[whatever]file` naming scheme:

- [Brew Bundle](https://github.com/Homebrew/homebrew-bundle): `Brewfile`
- [Rake](http://rake.rubyforge.org/): `Rakefile`
- [Bundler](http://bundler.io/): `Gemfile`
- [make](http://linux.about.com/library/cmd/blcmdl1_make.htm): `makefile`

Pretty Ruby-heavy, huh? I'm not even a Ruby developer, just noticed...

Reviewing the fish documentation and all configuration files, I've come to prefer a whole other name. Why not just name it exactly analog to what it contains: `plugins`?

Reasoning:

1. The file will not contain any commands, hence a `.fish` suffix is out of the question.
2. The `[whatever]file` specifications listed above all contain special markup and/or commands along with the actual links to the payload.
3. A clean name that can be used across projects should be preferred.
4. The goal should be to make things as simple as possible.

What do you think, @fishery/all?

PS: I took the liberty to create a new team containing all members, so everyone in Fishery can be notified with one `@`. If you don't like that, please let me know.

**Comment by orangecms** [comment]
Just `plugins` would be too generic and may provoke collisions. The `*file` naming scheme is being used for build instructions, as @herrbischoff pointed out. My suggestion would be `finrc`, that is most common.

**Comment by herrbischoff** [comment]
@orangecms: Good point but wouldn't solve the issue with having *one* name across Fisherman and fin.

**Comment by orangecms** [comment]
I'm not even sure if that's a very good idea anyway. Either use fisherfile and claim that fin is compatible with fisherman, or give it a different name.

**Comment by bucaran** [comment]
@herrbischoff 

> I took the liberty to create a new team containing all members, so everyone in Fishery can be notified with one @. If you don't like that, please let me know.

Not at all, thank you so much.

So, for the looks of it, it seems we are going to go with `fishfile` after all.

**Comment by jethrokuan** [comment]
Yes, the syntax of the "fishfile" for fin and fisherman is exactly the same, and thus fisherman and fin are completely compatible.

**Comment by bucaran** [comment]
Small correction: both fishfiles would be 99% compatible, except for how we handle gists. fin's gist handling is different from fisherman. In fisherman we embed the name in the string, whereas in fin we just add the url to the file as a comment.

**Comment by pickfire** [comment]
1 more vote to `fishers` or `fishery`

**Comment by bucaran** [comment]
@pickfire Haha what?

**Comment by lordlycastle** [comment]
How about `.fiss`? Got a nice tone to it 😉

**Comment by lordlycastle** [comment]
And for the real reason this topic was made, I concur that two character commands are better than one, it's easier to remember and understand.

**Comment by bucaran** [comment]
@lordlycastle Yeah, I updated the README to show `fin up`, but you can use `update` and completions also work for all the variations.

**Comment by orangecms** [comment]
2 char commands are like openSUSE's zypper, their system package manager wrapping around rpm btw. Maybe for consistency fin could use the same. They also have up, rm and in.

**Comment by bucaran** [comment]
Closing as the README has already been updated to use `fin up` instead of `fin update` and the rest of the examples are already using the 2 char form of the commands.

Just for the record in case somewhere stumbles upon this and thinks `fin`'s commands are only 2 char. They are *not*. We are only using the 2 char form of the commands in the README for aesthetic purposes. fin supports the following command and aliases:


```
fin -h
Usage: fin [<command>] [<plugins>] [--quiet] [--version]

where <command> can be one of:
       install (default)
       update
       rm
       ls
       help
```

* install, in, i (or nothing, this is fin's default command to install/enable/switch plugins/themes)
* update, up, u
* remove, rm, r (uninstall also works)
* list, ls, l
* h help
